# Generated by Django 4.2.7 on 2024-05-28 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="approved",
            new_name="is_approved",
        ),
    ]
